<a href="https://colab.research.google.com/github/TaylorShiehUSI/Github-Colab-test/blob/main/homework_20220809_final_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
% reset
import requests as r
import json
import pandas as pd
from datetime import datetime, date
import matplotlib.pyplot as plt
%matplotlib inline

Once deleted, variables cannot be recovered. Proceed (y/[n])? y

In [6]:
#pd.date_range('2022-08-01', '2022-08-05', freq='D').strftime("%Y%m%d").tolist()

# Datestrlist Gen
#datestrlist = ['20220801','20220802','20220803','20220804','20220805']
datestrlist= pd.date_range('2022-08-01', '2022-08-05', freq='D').strftime("%Y%m%d").tolist()
datestrlist

# for day in date_list:
#     print(day)

['20220801', '20220802', '20220803', '20220804', '20220805']

In [7]:
## Ref to https://www.youtube.com/watch?v=_4CEymrQbV8 Youtube Example
## Get resonponse

## Creating Head
#columns = ['代號', '證券名稱', '成交股數', '成交筆數', '成交金額', '開盤價', '最高價', '最低價', '收盤價','漲跌','漲跌價差','最後揭示買價','最後揭示買量','最後揭示賣價','最後揭示賣量','表益比']
#stock_df=pd.DataFrame
#stock_df.cloumns=columns

## 下載股價 with JSON
for date in datestrlist:
  res= r.get('https://www.twse.com.tw/exchangeReport/MI_INDEX?response=json&date=' + date + '&type=ALL')
  stock_json=res.json()
  # stock message in data9
  stock_df=pd.DataFrame.from_dict(stock_json['data9'])
  stock_df.columns=stock_json['fields9']
  stock_df.to_csv(str(date))
  #stock_df.to_csv(f'{date}.csv',encoding='utf-8_sig')

In [ ]:
stock_df.head()

,證券代號,證券名稱,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌(+/-),漲跌價差,最後揭示買價,最後揭示買量,最後揭示賣價,最後揭示賣量,本益比
0,0050,元大台灣50,"9,625,538","10,809","1,143,739,838",118.00,119.50,117.90,119.50,<p style= color:red>+</p>,2.95,119.45,73,119.50,116,0.00
1,0051,元大中型100,"23,695",127,"1,248,066",52.50,52.80,52.50,52.70,<p style= color:red>+</p>,0.70,52.65,1,52.70,4,0.00
2,0052,富邦科技,"386,618",553,"38,782,188",99.30,100.85,99.30,100.85,<p style= color:red>+</p>,2.55,100.80,1,100.85,1,0.00
3,0053,元大電子,"10,072",972,"580,068",57.45,57.70,57.45,57.70,<p style= color:red>+</p>,1.20,57.70,1,57.75,5,0.00
4,0055,元大MSCI金融,"731,618",625,"16,665,972",22.62,22.89,22.62,22.88,<p style= color:red>+</p>,0.33,22.88,4,22.89,1,0.00